count_edges: count_edges.cpp
	g++ -O3 -Wall count_edges.cpp -o count_edges
	

generateweights: distances.cpp
	g++ -O3 -Wall distances.cpp -o generateweights


clean:
	rm -v count_edges generateweights
